server:
    port: 5689 #启动端口

spring:
    application:
        name: ace-sidecar-client-demo

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/